development:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: <%= ENV["DATABASE_NAME"] || 'facenote_development' %>
  pool: 5
  username: <%= ENV["DATABASE_USR"] || 'postgres' %>
  password: <%= ENV["DATABASE_PWD"] || 'postgres' %>

test:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: facenote_test<%= ENV["TEST_ENV_NUMBER"] %>
  pool: 5
  username: <%= ENV["DATABASE_USR"] || 'postgres' %>
  password: <%= ENV["DATABASE_PWD"] || 'postgres' %>

staging:
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 15 %>

production:
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 15 %>
