

development:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: <%= ENV["DATABASE_NAME"] || 'facenote_development' %>
  pool: 5
  username: <%= ENV["DATABASE_USR"] || 'postgres' %>
  password: <%= ENV["DATABASE_PWD"] || 'postgres' %>

test:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: facenote_test<%= ENV["TEST_ENV_NUMBER"] %>
  pool: 5
  username: <%= ENV["DATABASE_USR"] || 'postgres' %>
  password: <%= ENV["DATABASE_PWD"] || 'postgres' %>

production:
  adapter: <%= ENV["adapter"] %>
  encoding: <%= ENV['encoding'] %>
  host: <%= ENV["host"] %>
  port: <%= ENV["port"] %>
  username:  <%= ENV["username"] %>
  password:  <%= ENV["password"] %>
  database: <%= ENV["database"] %>
  poll: <%= ENV["poll"] %>
