# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 208d22a658d1a77b1cb62679a102fbc18fc0a1d7bcdf71e4b17d9ad344a65a28b76c8154a010d1b364b24e384b9fd54c34e7b8b066ec90743e518df0fa69c68e

test:
  secret_key_base: fbe48bfc38f612658df386d7f9104d481e4c0b0f34b800ec58e64669a439cbc9a9a3483b75f4429d3c4ba64eecce686a7e789a83becd2751da1e5897575b8c93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
